baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Blog by will"
copyright = "This is a customized copyright."
theme = "diary"

# defaultContentLanguageInSubdir = true
# [languages]
#   [languages.en]
#     # baseURL = 'https://en-us.example.org/'
#     contentDir = 'content/en-us'
#     disabled = false
#     languageCode = 'en-US'
#     languageDirection = 'ltr'
#     languageName = 'English'
#     title = "Meswsoul's Blog"
#     weight = 1
#     [languages.en.params]
#       subtitle = 'Reference, Tutorials, and Explanations'
#       color = 'red'
#     [languages.en.menu]
#       [[languages.en.menu.main]]
#         name = "Home"
#         url = "/"
#         weight = 1
#     [[languages.en.menu.main]]
#         name = "About"
#         url = "/about/"
#         weight = 6
# 
# 
#   [languages.zh]
#     # baseURL = 'https://zh-tw.example.org/'
#     contentDir = 'content/zh-tw'
#     disabled = false
#     languageCode = 'zh-tw'
#     languageDirection = 'ltr'
#     languageName = '中文'
#     title = "Meswsoul's 部落格"
#     weight = 2
#     [languages.zh.params]
#       subtitle = 'Referenz, Tutorials und Erklärungen'
#       color = 'blue'
#     [languages.zh.menu]
#       [[languages.zh.menu.main]]
#         name = "首頁"
#         url = "/"
#         weight = 1
#       [[languages.zh.menu.main]]
#         name = "關於"
#         url = "/about/"
#         weight = 2


# Generate sitemap in the public folder
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-XXXXXXXXXX"  # Your Google Analytics ID

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Themed by Diary."
enableGitalk = false
enableGiscus = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="username/repo"
    data_repo_id="**************************"    
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 6

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2

# [[menu.main]]
# name = "Blog"
# url = "/posts/"
# weight = 3

# [[menu.main]]
# name = "RSS Feed"
# url = "/index.xml"
# weight = 4
